### ISSUE TITLE
gimp-delete-image not found

### ISSUE THREAD

**Issue by map7** [dmig/gimp-scan-cutter#1]
Using Gimp 2.8 under Linux Mint 18.2 the cutter works, but the batch doesn't. After at's finished with the first photo and tries to run gimp-delete-image it fails.

Error from gimp
```
Calling error for procedure 'gimp-procedural-db-proc-info':
Procedure 'gimp-delete-image' not found
```

Trace
```
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 736, in response
    dialog.res = run_script(params)
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/home/amandaep/.gimp-2.8/plug-ins/gimp-scan-cutter.py", line 276, in cutter_batch_images
    pdb.gimp_delete_image(image)
error: procedure not found
```

**Comment by dmig-alarstudios** [comment]
looks like, something changed in the recent GIMP... needs discovering.
pull requests are welcome.

**Comment by dmig** [comment]
looks like, something changed in the recent GIMP... needs discovering.
pull requests are welcome.

**Comment by map7** [comment]
I just remarked out the line for now and I got my batch done. I'll look at
a proper solution if I have time.

**Comment by smokinfiddler** [comment]
I seemed to have fixed it by changing that line to 
`pdb.gimp_image_delete(image)`

I will try and correct it in a pull request once I have some time.
